IF YEAR(CURRENT_TIMESTAMP) = '2022'
BEGIN
	PRINT '1'
END
ELSE
BEGIN
	PRINT '2'
END

-----


DECLARE @year AS INT = YEAR(CURRENT_TIMESTAMP)

SELECT *
FROM SFM.dbo.Users
WHERE YEAR(FirstReg) = @year



----
DECLARE @year AS INT = YEAR(CURRENT_TIMESTAMP)

--SELECT CONCAT(CONVERT(VARCHAR, @year),'-02-29')
SELECT *
FROM SFM.dbo.Users
--WHERE CONVERT(VARCHAR,(YEAR(FirstReg))) = CONCAT(CONVERT(VARCHAR, @year),'-02-29')
WHERE CONVERT(DATE,(FirstReg)) = CONCAT(CONVERT(VARCHAR, @year),'-02-29')


